In [3]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df=pd.read_csv("7-cyber_attack_data.csv")

In [5]:
df.head()


src_packet_rate  dst_packet_rate  avg_payload_size  connection_duration  \
0        -1.286132        -0.648334          1.044115            -0.469715   
1        -0.222224         2.083232          1.191114            -1.354527   
2        -0.431963         0.375745         -1.370334             0.819214   
3        -0.912633         0.986988         -0.690042             2.014628   
4        -0.367056         1.667892          0.879172             2.214276   

   tcp_flag_count  avg_interarrival_time  failed_login_attempts  \
0        0.789859              -0.083727              -1.647309   
1       -0.956992               1.696028              -1.070406   
2        0.345243               1.389447              -1.904130   
3       -0.442260               0.590347              -1.819353   
4        1.846338              -0.894047               1.543838   

   unusual_port_activity_score  session_entropy  avg_response_delay  \
0                    -1.316412         1.011910           -0.898063   
1                     0.981403        -1.628798            1.377594   
2                     1.292602         0.925545            0.232705   
3                     1.560938         0.823755            0.517762   
4                     0.931103        -1.015210            1.061845   

   attack_type  
0            2  
1            0  
2            0  
3            0  
4            1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   src_packet_rate              1000 non-null   float64
 1   dst_packet_rate              1000 non-null   float64
 2   avg_payload_size             1000 non-null   float64
 3   connection_duration          1000 non-null   float64
 4   tcp_flag_count               1000 non-null   float64
 5   avg_interarrival_time        1000 non-null   float64
 6   failed_login_attempts        1000 non-null   float64
 7   unusual_port_activity_score  1000 non-null   float64
 8   session_entropy              1000 non-null   float64
 9   avg_response_delay           1000 non-null   float64
 10  attack_type                  1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [7]:
from sklearn.model_selection import train_test_split

In [14]:
X=df.drop(columns="attack_type",axis=1)
y=df["attack_type"]

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
regression=LogisticRegression()

In [25]:
regression.fit(X_train,y_train)

LogisticRegression()

In [26]:
regression.coef_

array([[-7.77667665e-01,  6.66404472e-01, -3.99358956e-02,
        -9.10755932e-02, -5.41898869e-02,  1.50501287e-02,
        -9.26199749e-02,  9.22298591e-01,  6.07830098e-01,
         2.92719204e-01],
       [ 7.76844520e-01, -2.78073455e-01,  8.06479925e-02,
         8.58496914e-02, -6.00700832e-02,  5.16473141e-02,
         1.66573379e-01,  2.34550215e-01, -2.07222876e-01,
         5.85228826e-02],
       [ 8.23144792e-04, -3.88331017e-01, -4.07120969e-02,
         5.22590186e-03,  1.14259970e-01, -6.66974428e-02,
        -7.39534042e-02, -1.15684881e+00, -4.00607222e-01,
        -3.51242086e-01]])

In [27]:
regression.intercept_

array([-0.71387304,  0.20953934,  0.5043337 ])

In [28]:
y_pred=regression.predict(X_test)

In [29]:
y_pred

array([2, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 0, 1, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       0, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 2, 0, 0, 2, 2, 2])

In [30]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [36]:
score=accuracy_score(y_test,y_pred)
classifiction_report=classification_report(y_test,y_pred)
matrix=confusion_matrix(y_test,y_pred)
print("score :",score,"\n classifiction_report :", classifiction_report, "\n confusion_matrix :" , matrix)

score : 0.796 
 classifiction_report :               precision    recall  f1-score   support

           0       0.86      0.83      0.84        78
           1       0.82      0.75      0.78        91
           2       0.73      0.81      0.77        81

    accuracy                           0.80       250
   macro avg       0.80      0.80      0.80       250
weighted avg       0.80      0.80      0.80       250
 
 confusion_matrix : [[65  8  5]
 [ 3 68 20]
 [ 8  7 66]]


In [37]:
from sklearn.multiclass import OneVsOneClassifier,OneVsRestClassifier

In [52]:
onevsonecls=OneVsOneClassifier(LogisticRegression())


In [53]:
onevsrestcls=OneVsRestClassifier(LogisticRegression())

In [54]:
onevsonecls.fit(X_train,y_train)

OneVsOneClassifier(estimator=LogisticRegression())

In [55]:
y_pred2=onevsonecls.predict(X_test)

In [56]:
y_pred2

array([2, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 1, 2, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2, 2, 2, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       0, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 2, 0, 0, 2, 2, 2])

In [57]:
score=accuracy_score(y_test,y_pred2)
classifiction_report=classification_report(y_test,y_pred2)
matrix=confusion_matrix(y_test,y_pred2)
print("score :",score,"\n classifiction_report :", classifiction_report, "\n confusion_matrix :" , matrix)

score : 0.792 
 classifiction_report :               precision    recall  f1-score   support

           0       0.86      0.83      0.84        78
           1       0.83      0.74      0.78        91
           2       0.71      0.81      0.76        81

    accuracy                           0.79       250
   macro avg       0.80      0.79      0.79       250
weighted avg       0.80      0.79      0.79       250
 
 confusion_matrix : [[65  6  7]
 [ 4 67 20]
 [ 7  8 66]]
