In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("6-bank_customers.csv")

In [3]:
df.head()

age  job_satisfaction   balance  duration_last_call  \
0 -0.377957          1.043895  1.043494           -0.101838   
1 -0.325259          1.276263 -0.686123           -2.463205   
2  0.739019         -0.600903 -0.177294            1.335714   
3  0.474312         -1.103002  1.189936           -0.800186   
4  0.927365          1.114796  0.080284            1.261064   

   num_contacts_last_month  has_housing_loan  has_personal_loan  \
0                -1.617442          0.402713           0.913601   
1                -0.489426         -0.240715          -1.469496   
2                -0.817332         -0.790047           1.457365   
3                 0.912377         -0.406451          -1.130950   
4                 0.761179          0.921563           0.440832   

   communication_type  days_since_last_contact  campaign_response_score  \
0           -0.067192                 0.175471                -1.049646   
1            1.006633                -0.833692                 0.957744   
2           -0.218981                 0.878643                -1.257740   
3            1.985111                 1.379029                 1.041768   
4            0.184645                -1.567739                -0.142107   

   subscribed  
0           0  
1           0  
2           0  
3           1  
4           1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [6]:
X=df.drop(columns="subscribed",axis=1)
y=df["subscribed"]

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logistic=LogisticRegression()

In [13]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [14]:
logistic.coef_

array([[ 0.23269302,  0.01893953, -0.08949875,  0.83600874,  2.13066943,
         0.11035502, -0.69970836, -0.06550885,  0.1126568 ,  1.0147072 ]])

In [15]:
logistic.intercept_

array([0.67335062])

In [16]:
y_pred1=logistic.predict(X_test)

In [17]:
y_pred1

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1])

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [23]:
accuracy=accuracy_score(y_test,y_pred1)
confusion_mtrx=confusion_matrix(y_test,y_pred1)
classification=classification_report(y_test,y_pred1)

In [25]:
print("accuracy:",accuracy)
print("confusion_mtrx:",confusion_mtrx)
print("classification:",classification)

accuracy: 0.924
confusion_mtrx: [[121   8]
 [ 11 110]]
classification:               precision    recall  f1-score   support

           0       0.92      0.94      0.93       129
           1       0.93      0.91      0.92       121

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250



In [26]:
regression=LogisticRegression()

In [50]:
penalyts=["l1","l2","elasticnet"]
c_values=[100,10,1,0.1]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga','lbfgs']
dictionary=dict(C=c_values,penalty=penalyts,solver=solver)

In [1]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [2]:
cv=StratifiedKFold()

In [3]:
grid=GridSearchCV(estimator=regression,param_grid=dictionary,cv=cv,scoring="accuracy",n_jobs=-1)

NameError: name 'regression' is not defined

In [54]:
grid.fit(X_train,y_train)

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
240 fits failed out of a total of 420.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _ch

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga',
                                    'lbfgs']},
             scoring='accuracy')

In [55]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [56]:
grid.best_score_

np.float64(0.924)

In [73]:
grid.best_estimator_

LogisticRegression(C=0.1, penalty='l1', solver='liblinear')

In [74]:
grid.classes_

array([0, 1])

In [75]:
y_pred2=grid.predict(X_test)

In [76]:
accuracy=accuracy_score(y_test,y_pred2)
confusion_mtrx=confusion_matrix(y_test,y_pred2)
classification=classification_report(y_test,y_pred2)

In [77]:
print("accuracy:",accuracy)
print("confusion_mtrx:",confusion_mtrx)
print("classification:",classification)

accuracy: 0.932
confusion_mtrx: [[124   5]
 [ 12 109]]
classification:               precision    recall  f1-score   support

           0       0.91      0.96      0.94       129
           1       0.96      0.90      0.93       121

    accuracy                           0.93       250
   macro avg       0.93      0.93      0.93       250
weighted avg       0.93      0.93      0.93       250



In [78]:
from sklearn.model_selection import RandomizedSearchCV

In [82]:
search=RandomizedSearchCV(param_distributions=dictionary,n_jobs=-1,estimator=regression,cv=5,n_iter=10,scoring="accuracy")

In [83]:
search.fit(X_train,y_train)

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1, 0.1],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga', 'lbfgs']},
                   scoring='accuracy')

In [89]:
search.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [90]:
search.best_estimator_

LogisticRegression(C=0.1)

In [91]:
search.best_score_

np.float64(0.916)

In [92]:
search.classes_

array([0, 1])

In [93]:
search.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [94]:
y_pred3=logistic.predict(X_test)

In [95]:
y_pred3


array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1])

In [98]:
accuracy=accuracy_score(y_test,y_pred3)
confusion_mtrx=confusion_matrix(y_test,y_pred3)
classification=classification_report(y_test,y_pred3)

In [99]:
print("accuracy:",accuracy)
print("confusion_mtrx:",confusion_mtrx)
print("classification:",classification)


accuracy: 0.924
confusion_mtrx: [[121   8]
 [ 11 110]]
classification:               precision    recall  f1-score   support

           0       0.92      0.94      0.93       129
           1       0.93      0.91      0.92       121

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250

